"""scripts/cleanup_kg_noise.py — 清理 KG 旧数据噪声实体。

只保留白名单实体，删除所有不在白名单中的实体及关联关系。
白名单：EntityRegistry 的 confirmed 实体 + GARBAGE_ENTITIES（这些也应被过滤掉）。
"""

import sqlite3
import sys
import os

# 白名单（与 EntityRegistry 已注册的 confirmed 一致）
WHITELIST = {
    "王哥", "倪海厦",
    "Obsidian", "pudica-memory", "Hermes Agent", "Codex CLI", "DSH", "ARK", "Ollama", "微信",
    "天保GEF项目", "林草局", "腾讯", "阿里云", "ECS",
}

# 垃圾实体（GARBAGE_ENTITIES 中的，也应当删除）
GARBAGE = {
    "general", "unknown", "default", "system", "user", "assistant", "tool",
    "message", "conversation", "session", "chat", "bot", "agent",
    "memory", "content", "context", "query", "result", "response",
    "type", "name", "value", "key", "id", "data", "info", "text",
    "file", "path", "dir", "config", "setting", "option", "mode", "flag",
    "time", "date", "status", "error", "warning", "info", "debug", "log",
    "function", "class", "method", "module", "package", "library", "api",
    "project", "repo", "branch", "commit", "merge", "pr", "issue",
    "test", "build", "deploy", "release", "version", "tag",
    "python", "js", "ts", "go", "rust", "java", "cpp", "c",
    "windows", "linux", "macos", "android", "ios",
    "local", "remote", "server", "client", "host", "port",
    "install", "setup", "config", "init", "start", "stop", "restart",
    "run", "exec", "cmd", "shell", "bash", "zsh", "powershell",
    "http", "https", "ws", "wss", "tcp", "udp", "ip", "dns",
    "json", "xml", "yaml", "toml", "csv", "txt", "md", "html",
    "do", 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
    "GARBAGE_ENTITIES", "co_occurs_with", "related_to",
    "claude", "deepseek", "openai", "gpt", "gpt4", "gpt35",
    "qwen", "yi", "glm", "baichuan", "minimax", "moonshot",
    "langchain", "llamaindex", "autogen", "crewai", "pydantic",
    "fastapi", "flask", "django", "tornado", "aiohttp",
    "docker", "k8s", "kubernetes", "nginx", "redis", "postgres",
    "mysql", "sqlite", "mongodb", "elasticsearch",
    "github", "gitlab", "bitbucket", "git",
    "vscode", "vim", "emacs", "neovim", "intellij", "pycharm",
    "chrome", "firefox", "safari", "edge", "brave",
    "mac", "win", "ubuntu", "centos", "debian", "alpine",
    "aws", "gcp", "azure", "aliyun", "tencent", "huawei",
    "wechat", "qq", "dingtalk", "feishu", "slack", "discord", "telegram",
    "notion", "obsidian", "evernote", "onenote", "roam",
    "jupyter", "colab", "kaggle", "huggingface",
    "pytorch", "tensorflow", "jax", "onnx", "triton",
    "numpy", "pandas", "scipy", "sklearn", "matplotlib",
    "transformers", "diffusers", "sentence_transformers",
    "token", "embedding", "vector", "dimension", "dim",
    "batch", "epoch", "lr", "loss", "acc", "f1", "auc",
    "train", "val", "test", "infer", "predict",
    "prompt", "completion", "temperature", "top_p", "top_k",
    "stream", "sync", "async", "callback", "webhook",
    "auth", "login", "logout", "token", "session", "cookie",
    "permission", "role", "admin", "user", "guest",
    "production", "staging", "development", "testing",
    "ui", "ux", "gui", "cli", "tui", "api", "sdk",
    "frontend", "backend", "fullstack", "middleware",
    "database", "cache", "queue", "storage", "compute",
    "worker", "scheduler", "cron", "job", "task",
    "monitor", "alert", "metric", "trace", "log",
    "security", "privacy", "compliance", "audit",
    "performance", "scalability", "reliability",
    "docker-compose", "makefile", "readme", "license",
    "changelog", "roadmap", "wiki", "docs",
    "todo", "fixme", "hack", "workaround",
    "bug", "feature", "enhancement", "refactor",
    "hotfix", "patch", "minor", "major",
    "alpha", "beta", "rc", "stable", "latest",
    "v1", "v2", "v3", "v4", "v5",
    "protocol", "format", "schema", "contract",
    "input", "output", "io", "stdin", "stdout", "stderr",
    "src", "dist", "build", "lib", "bin", "etc",
    "init", "main", "index", "app", "server",
    "common", "utils", "helpers", "mixins", "base",
    "abstract", "interface", "impl", "concrete",
    "factory", "builder", "singleton", "proxy", "decorator",
    "observer", "publisher", "subscriber", "listener",
    "handler", "controller", "service", "repository",
    "model", "view", "presenter", "viewmodel",
    "entity", "value_object", "aggregate", "domain",
    "dto", "vo", "po", "bo", "do",
    "request", "response", "event", "command",
    "migration", "seed", "fixture", "factory",
    "mock", "stub", "fake", "spy", "dummy",
    "unit", "integration", "e2e", "smoke", "regression",
    "coverage", "quality", "lint", "format",
    "ci", "cd", "pipeline", "stage", "step",
    "artifact", "package", "bundle", "archive",
    "native", "cross", "platform", "portable",
    "32", "64", "128", "256", "384", "512", "768", "1024", "2048", "4096",
    "KB", "MB", "GB", "TB", "PB",
    "ms", "s", "min", "h", "d", "w", "mo", "y",
    "utf8", "utf-8", "ascii", "unicode", "gbk", "gb2312",
    "hint", "note", "tip", "warning", "caution", "danger",
    "section", "subsection", "chapter", "appendix",
    "var", "let", "const", "if", "else", "for", "while", "switch",
    "true", "false", "null", "none", "nil", "undefined",
    "yes", "no", "on", "off", "enable", "disable",
    "include", "exclude", "filter", "sort", "group",
    "add", "remove", "update", "delete", "create",
    "get", "set", "has", "is", "can", "should",
    "find", "search", "list", "show", "print",
    "open", "close", "read", "write", "save", "load",
    "export", "import", "upload", "download",
    "connect", "disconnect", "bind", "unbind",
    "lock", "unlock", "reserve", "release",
    "push", "pull", "fetch", "commit", "checkout",
    "merge", "rebase", "reset", "revert", "stash",
    "fork", "clone", "branch", "tag", "release",
    "star", "watch", "follow", "sponsor",
    "issue", "pr", "discussion", "wiki", "project",
    "assign", "label", "milestone", "board",
    "sprint", "backlog", "epic", "story", "task",
    "point", "estimate", "velocity", "burndown",
    "standup", "retro", "demo", "planning",
    "1st", "2nd", "3rd", "4th", "5th",
    "first", "second", "third", "fourth", "fifth",
    "last", "next", "prev", "current", "previous",
    "begin", "end", "middle", "top", "bottom",
    "left", "right", "center", "header", "footer",
    "inner", "outer", "inside", "outside",
    "up", "down", "in", "out", "over", "under",
    "before", "after", "during", "since", "until",
    "new", "old", "fresh", "stale", "expired",
    "active", "inactive", "pending", "done", "failed",
    "success", "pass", "fail", "skip", "block",
    "green", "red", "yellow", "blue", "white", "black",
    "normal", "important", "critical", "low", "high",
    "small", "medium", "large", "xl", "xxl",
    "min", "max", "avg", "sum", "total",
    "count", "size", "len", "length", "weight",
    "speed", "rate", "freq", "period", "interval",
    "source", "target", "dest", "origin",
    "from", "to", "via", "through", "across",
    "with", "without", "including", "excluding",
    "and", "or", "not", "xor", "nor",
    "all", "any", "some", "none", "each", "every",
    "both", "either", "neither", "other", "another",
    "this", "that", "these", "those",
    "here", "there", "where", "when", "how", "why",
    "what", "which", "who", "whom", "whose",
    "my", "your", "his", "her", "its", "our", "their",
    "I", "you", "he", "she", "it", "we", "they",
    "me", "him", "us", "them",
    "am", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "having",
    "do", "does", "did", "doing", "done",
    "will", "would", "shall", "should", "can", "could", "may", "might",
    "must", "need", "dare", "ought",
    "not", "no", "nor", "neither", "never",
    "very", "too", "so", "quite", "rather",
    "more", "less", "most", "least",
    "much", "many", "few", "little", "several",
    "good", "bad", "better", "worse", "best", "worst",
    "big", "small", "large", "huge", "tiny",
    "fast", "slow", "quick", "rapid", "gradual",
    "easy", "hard", "simple", "complex", "difficult",
    "cheap", "expensive", "free", "paid", "premium",
    "safe", "dangerous", "stable", "unstable",
    "clean", "dirty", "pure", "mixed",
    "full", "empty", "partial", "complete",
    "raw", "processed", "final", "intermediate",
    "unknown", "undefined", "unspecified",
    "approx", "roughly", "about", "around",
    "exact", "precise", "accurate", "correct",
    "possible", "probable", "likely", "unlikely",
    "always", "usually", "often", "sometimes", "rarely", "never",
    "maybe", "perhaps", "probably", "possibly",
    "yes", "yeah", "yep", "yup", "nope", "nah",
    "ok", "okay", "k", "kk", "fine",
    "hello", "hi", "hey", "yo", "sup",
    "thanks", "thx", "ty", "tks",
    "bye", "goodbye", "cya", "later", "peace",
    "lol", "lmao", "rofl", "wtf", "omg",
    "btw", "fyi", "imo", "imho", "tldr",
    "edit", "update", "fix", "patch", "hack",
    "workaround", "kludge", "temp", "temporary",
    "permanent", "final", "ultimate",
    "backup", "restore", "recover", "revert",
    "legacy", "deprecated", "removed", "archived",
    "experimental", "beta", "alpha", "dev", "nightly",
    "stable", "release", "production", "live",
    "internal", "external", "public", "private",
    "hidden", "visible", "invisible", "readonly",
    "editable", "writable", "readable", "executable",
    "optional", "required", "mandatory", "default",
    "custom", "builtin", "plugin", "extension",
    "core", "base", "root", "top", "leaf",
    "parent", "child", "sibling", "ancestor", "descendant",
    "primary", "secondary", "tertiary",
    "master", "slave", "main", "secondary",
    "single", "double", "triple", "quad",
    "mono", "bi", "tri", "multi", "poly",
    "half", "double", "triple", "quadruple",
    "once", "twice", "thrice",
    "zero", "one", "two", "three", "four", "five",
    "six", "seven", "eight", "nine", "ten",
    "hundred", "thousand", "million", "billion",
    "dozen", "score", "gross",
    "pair", "couple", "few", "several", "many",
    "single", "double", "triple", "multiple",
    "empty", "null", "void", "nil", "none",
    "nan", "inf", "infinity", "undefined",
    "true", "false", "boolean", "bool",
    "int", "float", "double", "decimal", "number",
    "string", "char", "bytes", "bytearray",
    "list", "array", "tuple", "set", "dict", "map",
    "object", "instance", "class", "type",
    "struct", "union", "enum", "interface",
    "generator", "iterator", "iterable",
    "coroutine", "future", "task", "thread",
    "process", "pool", "executor", "scheduler",
    "event", "signal", "callback", "handler",
    "loop", "select", "poll", "epoll", "kqueue",
    "socket", "connection", "stream", "pipe",
    "address", "port", "host", "path",
    "url", "uri", "urn", "slug",
    "scheme", "domain", "subdomain", "tld",
    "path", "query", "fragment", "params",
    "header", "body", "cookie", "session",
    "method", "verb", "action", "operation",
    "get", "post", "put", "patch", "delete", "head", "options",
    "status", "code", "reason", "message",
    "200", "201", "204", "301", "302", "400", "401", "403", "404", "405",
    "409", "422", "429", "500", "502", "503", "504",
    "json", "xml", "html", "text", "binary",
    "plain", "rich", "markdown", "html",
    "base64", "hex", "binary", "octal",
    "md5", "sha1", "sha256", "sha512",
    "aes", "rsa", "dsa", "ecdsa", "hmac",
    "cert", "key", "pem", "der", "crt",
    "ssl", "tls", "https", "wss",
    "cors", "csrf", "xss", "sqli", "rce",
    "oauth", "jwt", "saml", "oidc", "ldap",
    "basic", "bearer", "digest", "token",
    "encoding", "decoding", "encryption", "decryption",
    "compression", "decompression",
    "serialization", "deserialization",
    "validation", "verification", "sanitization",
    "normalization", "standardization",
    "aggregation", "transformation",
    "extraction", "loading", "transforming",
    "etl", "elt", "pipeline", "workflow",
    "ingestion", "processing", "output",
    "realtime", "batch", "streaming",
    "online", "offline", "hybrid",
    "cold", "hot", "warm", "tepid",
    "lazy", "eager", "greedy",
    "brute", "force", "naive", "smart",
    "linear", "binary", "log", "exp", "sqrt",
    "recursive", "iterative", "declarative",
    "functional", "oop", "procedural",
    "static", "dynamic", "duck", "nominal",
    "strong", "weak", "gradual", "latent",
    "typed", "untyped", "inferred",
    "compiled", "interpreted", "jit", "aot",
    "aarch64", "x86_64", "arm", "riscv",
    "simd", "avx", "sse", "neon", "sve",
    "cpu", "gpu", "tpu", "npu", "asic",
    "ram", "rom", "flash", "ssd", "hdd",
    "nvme", "sata", "pcie", "usb", "hdmi", "dp",
    "wifi", "bt", "ble", "nfc", "rfid",
    "4g", "5g", "lte", "nbiot", "lora",
    "gps", "bds", "glonass", "galileo",
    "soc", "mcu", "fpga", "asic",
    "kernel", "driver", "firmware", "bios",
    "boot", "loader", "initrd", "initramfs",
    "grub", "uboot", "coreboot", "libreboot",
    "systemd", "init", "upstart", "runit", "s6",
    "x11", "wayland", "xorg", "weston",
    "alsa", "pulse", "pipewire", "jack",
    "dbus", "dconf", "gsettings",
    "polkit", "consolekit", "logind",
    "pam", "nss", "ldap", "kerberos",
    "selinux", "apparmor", "tomoyo", "smack",
    "iptables", "nftables", "ebpf", "tc",
    "cgroup", "namespace", "chroot", "pivot",
    "capability", "seccomp", "landlock",
    "overlay", "aufs", "unionfs", "squashfs",
    "ext4", "btrfs", "xfs", "zfs", "ntfs", "fat32",
    "lvm", "raid", "mdadm", "dmcrypt",
    "fstab", "mtab", "crypttab", "cryptsetup",
    "loop", "device", "mapper", "multipath",
    "udev", "devtmpfs", "devfs",
    "sysfs", "procfs", "tmpfs", "ramfs",
    "acpi", "dt", "dtb", "dts", "overlay",
    "dmi", "smbios", "uefi", "bios", "efi",
    "mbr", "gpt", "partition", "volume",
    "swap", "zram", "zswap", "oom",
    "hugepage", "transparent", "thp",
    "numa", "cpuinfo", "meminfo", "loadavg",
    "uptime", "procs", "cpus", "mem",
    "top", "htop", "btm", "glances", "nmon",
    "ps", "kill", "pkill", "nice", "renice",
    "lsof", "fuser", "pidof", "pgrep",
    "strace", "ltrace", "gdb", "perf", "valgrind",
    "objdump", "readelf", "nm", "strings", "strip",
    "ldd", "ldconfig", "ld.so", "ld-linux",
    "ar", "ranlib", "nm", "objcopy", "objdump",
    "gcc", "g++", "clang", "clang++", "rustc",
    "as", "ld", "gold", "lld", "mold",
    "make", "cmake", "meson", "ninja", "bazel",
    "autoconf", "automake", "libtool", "pkgconfig",
    "configure", "m4", "bison", "flex", "yacc",
    "lex", "yacc", "bison", "flex",
    "antlr", "peg", "pegjs", "nearley", "ohm",
    "parser", "lexer", "tokenizer", "compiler",
    "interpreter", "vm", "runtime", "sdk",
    "bytecode", "ir", "ast", "cfg", "dfg",
    "ssa", "cfa", "dominator", "loop",
    "optimizer", "pass", "transform", "analysis",
    "inliner", "devirtualizer", "vectorizer",
    "unroller", "peephole", "constant",
    "dce", "cse", "gvn", "licm", "sccp",
    "register", "allocator", "scheduler",
    "spill", "remat", "coalesce", "split",
    "prologue", "epilogue", "frame", "stack",
    "abi", "calling", "convention", "mangling",
    "symbol", "section", "segment", "reloc",
    "debug", "dwarf", "stabs", "pdb",
    "coff", "elf", "macho", "pe", "wasm",
    "obj", "lib", "dll", "so", "dylib", "a", "exe",
    "static", "shared", "dynamic", "linked",
    "archive", "library", "module", "plugin",
    "header", "source", "object", "binary",
    "dependency", "transitive", "circular",
    "version", "semver", "range", "lock",
    "workspace", "monorepo", "multirepo",
    "submodule", "subtree", "subrepo",
    "remote", "origin", "upstream", "downstream",
    "tracking", "untracked", "staged", "unstaged",
    "index", "cache", "stage", "tree",
    "blob", "commit", "tree", "tag",
    "detached", "orphan", "bare", "mirror",
    "fastforward", "rebase", "merge", "squash",
    "undo", "redo", "revert", "cherry",
    "bisect", "blame", "annotate", "log",
    "diff", "patch", "format", "am",
    "send", "receive", "pack", "unpack",
    "gc", "repack", "prune", "fsck",
    "hook", "trigger", "action", "event",
    "pre", "post", "precommit", "postcommit",
    "prepush", "postpush", "premerge", "postmerge",
    "prereceive", "postreceive", "preupdate", "postupdate",
    "preapply", "postapply", "precheckout", "postcheckout",
    "prebuild", "postbuild", "preinstall", "postinstall",
    "prelink", "postlink", "preuninstall", "postuninstall",
    "preserve", "postserve", "prestop", "poststop",
    "group", "user", "other", "world",
    "owner", "group", "other", "all",
    "read", "write", "execute", "none",
    "allow", "deny", "grant", "revoke",
    "inherit", "propagate", "override",
    "policy", "rule", "acl", "capability",
    "trust", "verify", "validate", "sanitize",
    "allowlist", "blocklist", "greylist",
    "sandbox", "jail", "container", "vm",
    "orchestrate", "manage", "monitor", "scale",
    "provision", "configure", "deploy", "rollback",
    "health", "liveness", "readiness", "startup",
    "probe", "check", "test", "assert",
    "metric", "counter", "gauge", "histogram",
    "summary", "timer", "meter", "tracer",
    "span", "trace", "log", "event",
    "alert", "alarm", "notification", "pager",
    "escalate", "acknowledge", "resolve", "close",
    "sla", "slo", "sli", "error", "budget",
    "burn", "rate", "ratio", "threshold",
    "percentile", "p50", "p90", "p95", "p99", "p999",
    "qps", "rps", "tps", "iops", "bps",
    "latency", "throughput", "bandwidth",
    "availability", "reliability", "durability",
    "consistency", "partition", "tolerance",
    "cap", "base", "acid", "pacelc",
    "eventual", "strong", "causal", "read",
    "linearizable", "serializable", "snapshot",
    "mvcc", "2pl", "occ", "paxos", "raft",
    "zab", "viewstamped", "vr", "chain",
    "gossip", "epidemic", "swim", "serf",
    "consistent", "hash", "ring", "ketama",
    "rendezvous", "jump", "maglev",
    "shard", "partition", "replica", "node",
    "leader", "follower", "candidate", "observer",
    "quorum", "majority", "minority",
    "heartbeat", "lease", "epoch", "term",
    "timeout", "retry", "backoff", "jitter",
    "circuit", "breaker", "bulkhead", "retry",
    "rate", "limit", "throttle", "concurrency",
    "queue", "buffer", "pool", "slot",
    "worker", "dispatcher", "router", "balancer",
    "proxy", "gateway", "sidecar", "ambassador",
    "mesh", "ingress", "egress", "lb",
    "vip", "dns", "roundrobin", "leastconn",
    "hash", "sticky", "session", "persist",
    "blue", "green", "canary", "rolling",
    "ab", "split", "feature", "flag",
    "toggle", "switch", "config", "experiment",
    "gradual", "ramp", "rollout", "rollback",
    "migration", "schema", "data", "code",
    "sync", "async", "blocking", "nonblocking",
    "callback", "promise", "future", "deferred",
    "observable", "reactive", "stream", "pipeline",
    "monad", "functor", "applicative", "arrow",
    "category", "morphism", "object", "functor",
    "natural", "transformation", "adjunction",
    "product", "coproduct", "exponential",
    "limit", "colimit", "terminal", "initial",
    "pullback", "pushout", "equalizer", "coequalizer",
    "monoid", "semigroup", "group", "ring", "field",
    "vector", "matrix", "tensor", "scalar",
    "derivative", "integral", "gradient", "jacobian",
    "hessian", "laplacian", "curl", "div",
    "fft", "dct", "dst", "dwt", "hilbert",
    "convolution", "correlation", "pooling",
    "activation", "relu", "sigmoid", "tanh", "softmax",
    "attention", "transformer", "bert", "gpt",
    "encoder", "decoder", "embedding", "position",
    "head", "layer", "block", "module",
    "norm", "batch", "layer", "instance", "group",
    "dropout", "regularization", "normalization",
    "loss", "crossentropy", "mse", "mae", "hinge",
    "optimizer", "sgd", "adam", "adamw", "lamb",
    "lr", "schedule", "warmup", "decay", "cosine",
    "weight", "bias", "kernel", "filter",
    "channel", "feature", "map", "patch",
    "stride", "padding", "dilation", "kernel",
    "receptive", "field", "receptive_field",
    "residual", "skip", "connection", "shortcut",
    "dense", "conv", "pool", "rnn", "lstm", "gru",
    "bidirectional", "unidirectional", "causal",
    "mask", "padding", "attention", "causal",
    "teacher", "student", "distill", "prune",
    "quantize", "calibrate", "profile", "optimize",
    "fp32", "fp16", "bf16", "int8", "int4",
    "onnx", "tensorrt", "openvino", "coreml",
    "tflite", "neural", "engine", "nne",
    "vulkan", "directml", "cuda", "rocm", "mps",
    "cudnn", "cublas", "cufft", "curand", "cusparse",
    "nccl", "rccl", "mpi", "gloo", "ucl",
    "allreduce", "allgather", "broadcast", "reduce",
    "scatter", "gather", "alltoall", "sendrecv",
    "ring", "tree", "recursive", "halving",
    "sync", "async", "synchronous", "asynchronous",
    "barrier", "fence", "atomic", "lock",
    "mutex", "rwlock", "semaphore", "condition",
    "spinlock", "futex", "rcu", "seqlock",
    "channel", "mailbox", "queue", "ringbuf",
    "mpmc", "spmc", "mpsc", "spsc",
    "reader", "writer", "rwlock", "exclusive",
    "shared", "exclusive", "upgrade", "downgrade",
    "deadlock", "livelock", "starvation", "race",
    "safe", "unsafe", "sound", "complete",
    "memory", "order", "acquire", "release",
    "relaxed", "consume", "seqcst",
    "volatile", "atomic", "synchronized",
    "barrier", "fence", "compiler", "pipeline",
    "speculative", "outoforder", "superscalar",
    "pipeline", "hazard", "structural", "data",
    "control", "name", "war", "raw", "waw",
    "forward", "bypass", "stall", "flush",
    "branch", "predictor", "btb", "bimodal",
    "gshare", "tournament", "tage", "perceptron",
    "cache", "line", "set", "associative",
    "direct", "mapped", "fully", "associative",
    "l1", "l2", "l3", "llc", "snoop",
    "coherence", "mesi", "moesi", "directory",
    "inclusive", "exclusive", "noninclusive",
    "prefetch", "stream", "stride", "nextline",
    "tlb", "page", "table", "walk", "cache",
    "miss", "hit", "evict", "replace",
    "lru", "fifo", "random", "clock",
    "write", "through", "back", "allocate",
    "noallocate", "writeback", "writethrough",
    "read", "mostly", "readwrite", "execute",
    "noexec", "wxnx", "dep", "nx",
    "aslr", "pie", "pic", "relro", "canary",
    "fortify", "stack", "clash", "shadow",
    "sanitizer", "asan", "tsan", "msan", "ubsan",
    "lsan", "cfi", "kcfi", "cet", "ibt",
    "shadow", "stack", "indirect", "branch",
    "retpoline", "spectre", "meltdown", "l1tf",
    "mds", "zombieload", "fallout", "ridl",
    "srso", "entry", "bhi", "vmm",
    "hypervisor", "kvm", "xen", "vmware", "hyperv",
    "virtualbox", "qemu", "bhyve", "jailhouse",
    "acrn", "strato", "pvm", "lxc", "lxd",
    "openvz", "vserver", "singularity", "apptainer",
    "podman", "cri", "cri-o", "containerd",
    "docker", "moby", "pod", "sidecar",
    "init", "pause", "sandbox", "gvisor",
    "kata", "firecracker", "cloudhypervisor",
    "strato", "nabla", "unikraft", "osv",
    "linuxkit", "alpine", "busybox", "distroless",
    "scratch", "from", "base", "image",
    "layer", "manifest", "config", "tag",
    "registry", "hub", "repository", "namespace",
    "pull", "push", "build", "run", "exec",
    "attach", "logs", "inspect", "stats",
    "volume", "mount", "bind", "tmpfs",
    "network", "bridge", "host", "overlay",
    "macvlan", "ipvlan", "none", "custom",
    "port", "expose", "publish", "map",
    "compose", "stack", "service", "swarm",
    "secret", "config", "credential", "certificate",
    "dockerfile", "compose", "stack", "spec",
    "helm", "chart", "repo", "release",
    "kubeconfig", "context", "cluster", "namespace",
    "node", "pod", "service", "deployment",
    "statefulset", "daemonset", "job", "cronjob",
    "configmap", "secret", "pv", "pvc", "sc",
    "ingress", "egress", "service", "endpoint",
    "hpa", "vpa", "pdb", "networkpolicy",
    "rbac", "sa", "role", "clusterrole",
    "rolebinding", "clusterrolebinding",
    "crd", "cr", "webhook", "admission",
    "mutating", "validating", "conversion",
    "operator", "controller", "reconciler",
    "informers", "listers", "watchers", "caches",
    "apiserver", "scheduler", "controller", "etcd",
    "kubelet", "kubeproxy", "cni", "csi",
    "calico", "flannel", "weave", "cilium",
    "kubeadm", "kubespray", "kops", "kind",
    "minikube", "microk8s", "k3s", "k0s",
    "openshift", "rancher", "tanzu", "gke",
    "eks", "aks", "oke", "digitalocean",
    "scaleway", "vultr", "linode", "hetzner",
    "ovh", "ionos", "contabo", "netcup",
    "strato", "1and1", "godaddy", "namecheap",
    "cloudflare", "akamai", "fastly", "cloudfront",
    "varnish", "squid", "traffic", "server",
    "haproxy", "nginx", "apache", "caddy",
    "traefik", "envoy", "linkerd", "istio",
    "consul", "etcd", "zookeeper", "eureka",
    "nacos", "apollo", "spring", "cloud",
    "kafka", "pulsar", "rabbitmq", "activemq",
    "nats", "jetstream", "zeromq", "nanomsg",
    "redis", "memcached", "hazelcast", "ignite",
    "couchbase", "cassandra", "scylla", "hbase",
    "bigtable", "spanner", "cockroach", "yugabyte",
    "tidb", "oceanbase", "polardb", "aurora",
    "rds", "dynamodb", "documentdb", "neptune",
    "opensearch", "solr", "meilisearch", "typesense",
    "algolia", "elastic", "search", "enterprise",
    "splunk", "datadog", "newrelic", "dynatrace",
    "grafana", "prometheus", "thanos", "cortex",
    "loki", "tempo", "mimir", "alloy",
    "jaeger", "zipkin", "skywalking", "pinpoint",
    "datadog", "newrelic", "dynatrace", "appdynamics",
    "sentry", "rollbar", "bugsnag", "honeybadger",
    "pagerduty", "opsgenie", "victorops", "icinga",
    "nagios", "zabbix", "prometheus", "alertmanager",
    "ansible", "puppet", "chef", "salt",
    "terraform", "pulumi", "crossplane", "cdk",
    "packer", "vagrant", "waypoint", "nomad",
    "consul", "vault", "boundary", "sentinel",
    "jenkins", "teamcity", "bamboo", "circleci",
    "github", "actions", "gitlab", "ci", "travis",
    "codeship", "drone", "woodpecker", "buildkite",
    "argocd", "flux", "jenkins", "spinnaker",
    "harness", "octopus", "deploy", "ship",
    "sonar", "snyk", "dependabot", "renovate",
    "codeql", "semgrep", "gitleaks", "trufflehog",
    "eslint", "prettier", "black", "ruff",
    "mypy", "pyright", "pylint", "flake8",
    "bandit", "safety", "pip-audit", "pipenv",
    "poetry", "pdm", "hatch", "flit",
    "pip", "conda", "mamba", "micromamba",
    "brew", "apt", "yum", "dnf", "pacman",
    "choco", "scoop", "winget", "portage",
    "nix", "guix", "spack", "easybuild",
    "cargo", "npm", "yarn", "pnpm", "bun",
    "go", "mod", "dep", "vgo", "golang",
    "gem", "bundler", "rake", "gemspec",
    "nuget", "dotnet", "paket", "fake",
    "maven", "gradle", "ant", "sbt", "leiningen",
    "cabal", "stack", "hpack", "nix",
    "opam", "dune", "oasis", "jbuilder",
    "cpan", "cpanm", "carton", "perlbrew",
    "pip", "easy_install", "wheel", "egg",
    "pypi", "npm", "rubygems", "crates",
    "nuget", "maven", "central", "packagist",
    "homebrew", "linuxbrew", "macports", "fink",
    "snap", "flatpak", "appimage", "portable",
    "rpm", "deb", "pkg", "msi", "exe",
    "app", "dmg", "pkg", "bundle",
    "toolbox", "distrobox", "podman", "toolbox",
    "devcontainer", "codespace", "gitpod", "coder",
    "vscode", "dev", "container", "spec",
    "devfile", "dockerfile", "compose", "spec",
    "openapi", "swagger", "graphql", "grpc",
    "protobuf", "thrift", "avro", "parquet",
    "json", "yaml", "toml", "hcl", "dhall",
    "xml", "html", "css", "js", "ts",
    "wasm", "blazor", "silverlight", "flash",
    "java", "kotlin", "scala", "clojure", "groovy",
    "python", "ruby", "perl", "lua", "tcl",
    "php", "hack", "hhvm", "phpt",
    "javascript", "typescript", "coffeescript", "livescript",
    "c", "cpp", "c++", "c#", "objective-c",
    "swift", "rust", "go", "zig", "odin",
    "haskell", "ocaml", "f#", "sml", "coq",
    "idris", "agda", "lean", "purescript",
    "elixir", "erlang", "gleam", "caramel",
    "julia", "matlab", "r", "numpy", "scipy",
    "fortran", "cobol", "pascal", "ada", "lisp",
    "scheme", "racket", "clojure", "common", "lisp",
    "emacs", "lisp", "elisp", "guile",
    "prolog", "datalog", "souffle", "asp",
    "sql", "plsql", "tsql", "psql", "mysql",
    "nosql", "newsql", "graph", "document",
    "key", "value", "wide", "column", "time",
    "series", "object", "blob", "file",
    "relational", "dimensional", "multidimensional",
    "oltp", "olap", "htap", "h tap",
    "data", "warehouse", "lake", "mart",
    "etl", "elt", "data", "pipeline", "stream",
    "batch", "real", "time", "near", "real",
    "lambda", "kappa", "medallion", "bronze",
    "silver", "gold", "platinum",
    "staging", "raw", "refined", "curated",
    "dimension", "fact", "measure", "attribute",
    "snowflake", "star", "galaxy", "vault",
    "slowly", "changing", "dimension", "type",
    "scd", "type1", "type2", "type3", "type4",
    "conformed", "junk", "degenerate", "roleplaying",
    "bridge", "accumulating", "snapshot",
    "transaction", "periodic", "accumulating",
    "kimball", "inmon", "data", "vault",
    "lakehouse", "delta", "lake", "iceberg",
    "hudi", "carbon", "paimon", "delta",
    "spark", "flink", "beam", "storm", "heron",
    "mapreduce", "hadoop", "yarn", "hdfs",
    "hive", "presto", "trino", "impala",
    "drill", "tez", "pig", "sqoop", "flume",
    "kafka", "pulsar", "rabbitmq", "activemq",
    "nats", "jetstream", "pulsar", "kafka",
    "kinesis", "firehose", "pubsub", "eventhub",
    "stream", "processing", "event", "driven",
    "cqrs", "eventsourcing", "saga", "process",
    "orchestration", "choreography", "state",
    "machine", "state", "machine", "statemachine",
    "workflow", "pipeline", "dag", "task",
    "job", "step", "function", "action",
    "serverless", "lambda", "function", "cloud",
    "faas", "baas", "caas", "paas", "iaas",
    "saas", "daas", "maas", "xaas",
    "onprem", "cloud", "hybrid", "multi",
    "public", "private", "community", "sovereign",
    "edge", "fog", "cloudlet", "mist",
    "green", "brown", "colocation", "datacenter",
    "tier1", "tier2", "tier3", "tier4",
    "ups", "pdu", "crac", "chiller", "generator",
    "pue", "wue", "cue", "erf",
    "rto", "rpo", "mtd", "wrt",
    "backup", "restore", "replicate", "failover",
    "active", "passive", "activeactive", "hot",
    "cold", "warm", "standby", "spare",
    "disaster", "recovery", "dr", "bcdr",
    "business", "continuity", "resilience",
    "chaos", "engineering", "monkey", "army",
    "litmus", "gremlin", "chaosmesh", "chaosblade",
    "failure", "injection", "fault", "tolerance",
    "graceful", "degradation", "fallback", "circuit",
    "bulkhead", "timeout", "retry", "backoff",
    "rate", "limit", "concurrency", "throttle",
    "scale", "horizontal", "vertical", "auto",
    "elastic", "capacity", "planning", "sizing",
    "sla", "slo", "sli", "error", "budget",
    "availability", "uptime", "downtime", "reliability",
    "nine", "five", "three", "four", "six",
    "percent", "percentage", "ratio", "rate",
    "threshold", "baseline", "target", "goal",
    "kpi", "okr", "metric", "dashboard",
    "report", "analytics", "insight", "trend",
    "forecast", "predict", "estimate", "project",
    "cagr", "yoy", "mom", "qoq", "wow",
    "growth", "decline", "peak", "trough",
    "seasonal", "cyclic", "trend", "noise",
    "outlier", "anomaly", "spike", "drop",
    "mean", "median", "mode", "range",
    "variance", "stddev", "covariance", "correlation",
    "regression", "classification", "clustering",
    "dimensionality", "reduction", "pca", "tsne",
    "umap", "lle", "isomap", "mds",
    "svm", "rf", "gbm", "xgb", "lgbm",
    "cnn", "rnn", "lstm", "gru", "transformer",
    "gan", "vae", "diffusion", "normalizing",
    "reinforcement", "learning", "rl", "drl",
    "supervised", "unsupervised", "semi", "self",
    "transfer", "multitask", "meta", "fewshot",
    "zeroshot", "oneshot", "incontext", "prompt",
    "fine", "tune", "pretrain", "train",
    "inference", "serving", "deploy", "optimize",
    "distill", "prune", "quantize", "compress",
    "accelerate", "parallel", "distribute",
    "shard", "partition", "replicate", "cache",
    "offload", "swap", "pipeline", "tensor",
    "model", "parallelism", "data", "pipeline",
    "tensor", "sequence", "expert", "moefication",
    "moe", "gshard", "switch", "moe",
    "expert", "router", "gate", "capacity",
    "load", "balance", "auxiliary", "loss",
    "zloss", "importance", "smooth",
    "topk", "top2", "top1", "noisy",
    "hash", "random", "learned", "routing",
    "shared", "private", "expert", "specialist",
    "dense", "sparse", "mixture", "expert",
    "attention", "linear", "flash", "attention",
    "page", "attention", "vllm", "tgi",
    "triton", "inference", "server", "torchserve",
    "onnx", "runtime", "openvino", "tensorrt",
    "coreml", "nne", "tflite", "edgetpu",
    "nvidia", "amd", "intel", "apple", "google",
    "tpu", "gpu", "cpu", "npu", "dsp",
    "hbm", "gddr", "lpddr", "ddr", "sram",
    "flops", "tops", "tops", "tflops",
    "bandwidth", "throughput", "latency",
    "batch", "size", "sequence", "length",
    "context", "window", "max", "tokens",
    "tokenizer", "vocab", "embedding", "hidden",
    "layer", "head", "dimension", "ffn",
    "mlp", "activation", "gelu", "relu", "silu",
    "swiglu", "geglu", "reglu", "ffn",
    "norm", "rmsnorm", "layernorm", "batchnorm",
    "pre", "post", "norm", "sandwich",
    "residual", "skip", "connection", "shortcut",
    "rope", "alibi", "relative", "position",
    "absolute", "learned", "sinusoidal",
    "kv", "cache", "paged", "vllm", "sglang",
    "prefix", "caching", "radix", "tree",
    "speculative", "decoding", "draft", "verify",
    "medusa", "eagle", "lookahead", "selfspec",
    "blockwise", "parallel", "decoding",
    "cascade", "verification", "rejection",
    "sampling", "greedy", "beam", "topk",
    "topp", "temperature", "repetition", "penalty",
    "frequency", "presence", "diversity",
    "typical", "eta", "mirostat", "contrastive",
    "classifier", "free", "guidance", "cfg",
    "logit", "processor", "warp", "transform",
    "logits", "processor", "warp", "warp",
    "tail", "free", "sampling", "threshold",
    "epsilon", "cutoff", "eta", "cutoff",
    "minp", "topp", "topk", "typical",
    "repetition", "frequency", "presence",
    "temperature", "dynamic", "threshold",
    "adaptive", "sampler", "logit", "bias",
    "ban", "allow", "block", "good",
    "bad", "words", "ids", "token",
    "eos", "bos", "pad", "unk", "sep", "cls",
    "mask", "sos", "eol", "eof",
    "begin", "end", "separator", "padding",
    "unknown", "class", "mask", "segment",
    "special", "token", "added", "extra",
    "control", "token", "function", "call",
    "tool", "call", "function", "calling",
    "tool", "use", "tool", "calling",
    "parallel", "tool", "call", "multi",
    "streaming", "chunk", "delta", "event",
    "server", "sent", "event", "sse",
    "websocket", "ws", "grpc", "stream",
    "bidirectional", "unidirectional",
    "push", "pull", "pub", "sub",
    "request", "reply", "requestresponse",
    "fire", "forget", "async", "sync",
    "oneway", "twoway", "duplex",
    "rest", "graphql", "grpc", "soap",
    "jsonrpc", "xmlrpc", "thrift", "avro",
    "openapi", "swagger", "asyncapi", "graphql",
    "schema", "registry", "schema", "evolution",
    "backward", "forward", "full", "transitive",
    "compatible", "breaking", "deprecated",
    "required", "optional", "nullable",
    "enum", "oneof", "anyof", "allof", "not",
    "ref", "def", "path", "component",
    "security", "scheme", "bearer", "apikey",
    "oauth", "openid", "jwt", "saml",
    "rate", "limit", "quota", "throttle",
    "retry", "backoff", "circuit", "breaker",
    "idempotent", "safe", "cacheable",
    "conditional", "request", "etag",
    "lastmodified", "ifmatch", "ifnonematch",
    "ifmodified", "ifunmodified", "ifrange",
    "range", "content", "range", "partial",
    "accept", "contenttype", "encoding",
    "language", "charset", "negotiation",
    "content", "disposition", "filename",
    "multipart", "formdata", "urlencoded",
    "chunked", "transfer", "encoding",
    "compression", "gzip", "deflate", "br",
    "zstd", "compress", "identity",
    "keepalive", "connection", "upgrade",
    "websocket", "http2", "http3", "quic",
    "tls", "ssl", "sni", "alpn", "npn",
    "certificate", "chain", "intermediate",
    "root", "ca", "selfsigned", "letsencrypt",
    "acme", "dns01", "http01", "tlsalpn01",
    "wildcard", "san", "cn", "org",
    "validity", "expiry", "revocation",
    "crl", "ocsp", "stapling", "muststaple",
    "pinning", "hpkp", "expectct", "expectstaple",
    "csp", "hsts", "xfo", "xxp", "xss",
    "referrer", "policy", "permissions",
    "feature", "policy", "document", "policy",
    "cors", "origin", "accesscontrol",
    "alloworigin", "allowmethods", "allowheaders",
    "exposeheaders", "maxage", "credentials",
    "preflight", "simple", "request",
    "cookie", "session", "token", "jwt",
    "samesite", "secure", "httponly",
    "domain", "path", "maxage", "expires",
    "csrf", "token", "double", "submit",
    "synchronizer", "encrypted", "hmac",
    "captcha", "recaptcha", "hcaptcha", "turnstile",
    "rate", "limit", "brute", "force",
    "lockout", "account", "takeover",
    "credential", "stuffing", "spraying",
    "password", "hash", "bcrypt", "argon2",
    "scrypt", "pbkdf2", "salted", "pepper",
    "plaintext", "encrypted", "hashed",
    "salting", "peppering", "stretching",
    "key", "derivation", "hkdf", "pbkdf",
    "encryption", "aes", "chacha", "salsa",
    "twofish", "blowfish", "serpent", "des",
    "3des", "rc4", "rc5", "idea", "cast",
    "mode", "cbc", "ecb", "cfb", "ofb",
    "ctr", "gcm", "ccm", "eax", "siv",
    "padding", "pkcs7", "pkcs5", "oaep",
    "pss", "pkcs1", "v15", "v21",
    "rsa", "dsa", "ecdsa", "eddsa",
    "ecdh", "ecies", "dh", "elgamal",
    "curve", "p256", "p384", "p521", "x25519",
    "ed25519", "secp256k1", "bp256", "bp384",
    "key", "exchange", "agreement", "transport",
    "wrap", "unwrap", "encapsulate",
    "sign", "verify", "hash", "digest",
    "signature", "scheme", "rsassa", "ecdsa",
    "eddsa", "schnorr", "bls", "ring",
    "threshold", "multisig", "aggregate",
    "blind", "group", "proxy", "designated",
    "verifier", "undeniable", "failstop",
    "forward", "secure", "deniable",
    "nonrepudiation", "authenticity",
    "integrity", "confidentiality",
    "availability", "accountability",
    "auditability", "traceability",
    "provenance", "attestation", "notarization",
    "timestamp", "seal", "witness",
    "blockchain", "distributed", "ledger",
    "consensus", "pow", "pos", "dpos", "pbft",
    "hotstuff", "tendermint", "cosmos",
    "polkadot", "substrate", "near",
    "ethereum", "evm", "solidity", "vyper",
    "bitcoin", "script", "taproot", "schnorr",
    "lightning", "network", "ln", "rgb",
    "corda", "hyperledger", "fabric", "sawtooth",
    "iroha", "indy", "besu", "burrow",
    "quorum", " pantheon", "tessera", "orion",
    "privacy", "zero", "knowledge", "zkp",
    "snark", "stark", "bulletproof", "range",
    "proof", "circuit", "constraint", "witness",
    "prover", "verifier", "setup", "ceremony",
    "trusted", "setup", "toxic", "waste",
    "transparent", "universal", "updateable",
    "recursive", "aggregation", "accumulator",
    "polynomial", "commitment", "kzg",
    "pedersen", "elgamal", "fujisaki",
    "vector", "commitment", "merkle", "tree",
    "hash", "tree", "trie", "merkle", "patricia",
    "radix", "trie", "smt", "mpt", "patricia",
    "bloom", "filter", "cuckoo", "quotient",
    "xor", "filter", "gcs", "golomb",
    "hyperloglog", "countmin", "sketch",
    "bloom", "filter", "cuckoo", "filter",
    "simhash", "minhash", "locality", "sensitive",
    "lsh", "ann", "approx", "nearest", "neighbor",
    "kd", "tree", "vp", "tree", "r", "tree",
    "ball", "tree", "cover", "tree", "spill",
    "tree", "rp", "tree", "pq", "tree",
    "ivf", "hnsw", "nsg", "ssg", "efanna",
    "faiss", "scann", "annoy", "nmslib",
    "puffs", "titan", "milvus", "qdrant",
    "weaviate", "pinecone", "chroma", "vespa",
    "elasticsearch", "opensearch", "solr",
    "redisearch", "redisstack", "redislabs",
    "vald", "vearch", "jina", "marqo",
    "txtai", "langchain", "llamaindex",
    "semantic", "kernel", "aisql", "spacy",
    "stanza", "flair", "transformers",
    "sentence", "transformers", "tokenizers",
    "datasets", "evaluate", "accelerate",
    "huggingface", "hub", "model", "dataset",
    "space", "gradio", "streamlit", "bokeh",
    "dash", "plotly", "plotly", "dash",
    "shiny", "rstudio", "posit", "jupyter",
    "colab", "kaggle", "deepnote", "hex",
    "notebook", "lab", "hub", "enterprise",
    "jupyterlab", "notebook", "classic",
    "voila", "ipywidgets", "ipykernel",
    "ipython", "jupyter", "console", "qtconsole",
    "spyder", "pycharm", "vscode", "vim",
    "neovim", "emacs", "atom", "sublime",
    "textmate", "bbedit", "notepad", "notepadpp",
    "vim", "neovim", "spacemacs", "doomemacs",
    "vscode", "cursor", "windsurf", "zed",
    "helix", "kakoune", "vis", "acme",
    "sam", "ed", "ex", "vi", "nvi",
    "nano", "pico", "joe", "jstar",
    "mg", "uemacs", "zile", "jed",
    "dired", "ranger", "lf", "nnn",
    "vifm", "midnight", "commander", "mc",
    "fzf", "skim", "peco", "percol",
    "ripgrep", "rg", "ag", "ack", "grep",
    "find", "fd", "locate", "mlocate",
    "tree", "exa", "lsd", "eza",
    "bat", "cat", "ccat", "highlight",
    "delta", "diff", "diffso", "difftastic",
    "jq", "yq", "xq", "tq",
    "entr", "watch", "inotify", "fswatch",
    "tmux", "screen", "dtach", "abduco",
    "byobu", "terminator", "kitty", "alacritty",
    "wezterm", "ghostty", "foot", "st",
    "urxvt", "rxvt", "xterm", "terminal",
    "konsole", "gnome", "terminal", "xfce4",
    "deepin", "terminal", "alacritty",
    "kitty", "wezterm", "ghostty",
    "iterm2", "terminal", "hyper", "warp",
    "tabby", "terminus", "mobaxterm",
    "putty", "kitty", "mintty", "cygwin",
    "msys2", "mingw", "wsl", "wsl2",
    "bash", "zsh", "fish", "nu", "elvish",
    "xonsh", "powershell", "pwsh", "cmd",
    "sh", "dash", "ksh", "tcsh", "csh",
    "posix", "bourne", "shell", "bashism",
    "shebang", "env", "exec", "source",
    "alias", "export", "unset", "readonly",
    "function", "trap", "test", "let",
    "local", "global", "declare", "typeset",
    "printf", "echo", "read", "mapfile",
    "here", "doc", "here", "string", "process",
    "substitution", "command", "substitution",
    "arithmetic", "expansion", "brace",
    "tilde", "parameter", "variable",
    "globbing", "wildcard", "pattern",
    "regex", "extended", "glob", "globstar",
    "nullglob", "failglob", "dotglob",
    "nocaseglob", "globignore",
    "shopt", "set", "unset", "builtin",
    "enable", "disable", "type", "command",
    "hash", "cd", "pushd", "popd", "dirs",
    "pwd", "ls", "mkdir", "rmdir", "touch",
    "cp", "mv", "rm", "ln", "chmod",
    "chown", "chgrp", "umask", "stat",
    "dd", "tee", "cat", "tac", "rev",
    "head", "tail", "nl", "wc", "od",
    "sort", "uniq", "comm", "diff", "patch",
    "cut", "paste", "join", "tr", "expand",
    "unexpand", "fold", "fmt", "pr",
    "sed", "awk", "gawk", "mawk", "nawk",
    "perl", "python", "ruby", "lua", "tcl",
    "expect", "autoexpect", "empty",
    "cron", "at", "batch", "anacron",
    "service", "systemctl", "journalctl",
    "timedatectl", "hostnamectl", "localectl",
    "loginctl", "machinectl", "busctl",
    "sysctl", "modprobe", "insmod", "rmmod",
    "lsmod", "modinfo", "depmod",
    "dmesg", "journalctl", "logread",
    "kern", "user", "mail", "daemon",
    "auth", "syslog", "lpr", "news",
    "uucp", "cron", "local0", "local7",
    "fatal", "error", "warn", "info",
    "debug", "trace", "verbose",
    "emerg", "alert", "crit", "err",
    "warning", "notice", "info", "debug",
    "panic", "fatal", "error", "warn",
    "info", "debug", "trace", "silly",
    "log", "level", "facility", "priority",
    "syslog", "rsyslog", "syslogng", "journald",
    "logrotate", "logwatch", "logcheck",
    "graylog", "logstash", "fluentd", "fluentbit",
    "vector", "filebeat", "metricbeat",
    "packetbeat", "heartbeat", "winlogbeat",
    "elastic", "stack", "elk", "elastic",
    "opensearch", "graylog", "splunk",
    "sumologic", "logz", "datadog", "newrelic",
    "dynatrace", "signalfx", "wavefront",
    "influxdb", "timescaledb", "questdb",
    "clickhouse", "druid", "pinot", "kudu",
    "monetdb", "vertica", "redshift",
    "bigquery", "snowflake", "databricks",
    "athena", "presto", "trino", "spark",
    "hive", "impala", "drill", "tez",
    "mr", "mapreduce", "hadoop", "yarn",
    "hdfs", "s3", "gcs", "wasb", "adls",
    "minio", "ceph", "gluster", "moosefs",
    "nfs", "smb", "cifs", "samba",
    "fuse", "9p", "virtio", "plan9",
    "sshfs", "curlftpfs", "s3fs", "goofys",
    "rclone", "rsync", "unison", "syncthing",
    "nextcloud", "owncloud", "seafile",
    "dropbox", "googledrive", "onedrive",
    "icloud", "mega", "pcloud", "box",
    "backblaze", "wasabi", "idrive", "crashplan",
    "duplicity", "duplicati", "borg", "restic",
    "kopia", "restic", "borg", "duplicacy",
    "rclone", "gdrive", "s3", "b2",
    "tar", "gzip", "bzip2", "xz", "zstd",
    "zip", "rar", "7z", "arj", "cab",
    "lz4", "snappy", "lzo", "lzma",
    "zlib", "deflate", "gzip", "compress",
    "pack", "unpack", "archive", "extract",
    "compress", "decompress", "encode",
    "decode", "serialize", "deserialize",
    "marshal", "unmarshal", "pickle",
    "json", "yaml", "toml", "xml",
    "csv", "tsv", "ssv", "psv",
    "ini", "cfg", "conf", "config",
    "env", "properties", "plist", "reg",
    "rc", "profile", "bashrc", "zshrc",
    "vimrc", "tmuxconf", "gitconfig",
    "sshconfig", "sshdconfig", "resolv",
    "hosts", "hostname", "fstab", "mtab",
    "passwd", "shadow", "group", "gshadow",
    "sudoers", "suid", "sgid", "sticky",
    "cron", "anacron", "at", "batch",
    "crontab", "cron", "allow", "deny",
    "at", "allow", "deny", "batch",
    "anacron", "tab", "anacron",
    "logrotate", "conf", "logrotate",
    "syslog", "conf", "rsyslog", "conf",
    "journald", "conf", "systemd",
    "unit", "service", "socket", "timer",
    "target", "mount", "automount", "path",
    "scope", "slice", "swap", "device",
    "dropin", "override", "conf", "preset",
    "sysctl", "conf", "sysctl", "d",
    "modprobe", "conf", "modprobe", "d",
    "udev", "rules", "udev", "hwdb",
    "pam", "conf", "pam", "d",
    "security", "limits", "conf",
    "login", "defs", "profile",
    "bash", "bashrc", "bashprofile",
    "zsh", "zshrc", "zprofile", "zshenv",
    "zlogin", "zlogout",
    "profile", "bashprofile", "zprofile",
    "login", "shell", "interactive",
    "noninteractive", "login", "shell",
    "subshell", "child", "parent",
    "fork", "exec", "spawn", "clone",
    "pid", "ppid", "pgid", "sid",
    "uid", "euid", "suid", "gid",
    "egid", "sgid", "groups",
    "umask", "nice", "ionice", "chrt",
    "taskset", "numactl", "cgroups",
    "namespace", "pid", "net", "mnt",
    "ipc", "uts", "user", "cgroup",
    "time", "unshare", "nsenter",
    "capsh", "getcap", "setcap",
    "getfattr", "setfattr", "attr",
    "xattr", "lsattr", "chattr",
    "acl", "getfacl", "setfacl",
    "selinux", "chcon", "restorecon",
    "semanage", "seinfo", "sesearch",
    "apparmor", "aa", "status", "aa",
    "enforce", "aa", "complain", "aa",
    "audit", "aa", "logprof",
    "tomoyo", "ccs", "loadpolicy",
    "smack", "chsmack", "smackctl",
    "landlock", "restrict", "fs",
    "seccomp", "prctl", "seccomp",
    "sandbox", "bubblewrap", "firejail",
    "singularity", "apptainer", "udocker",
    "proot", "fakechroot", "fakeroot",
    "chroot", "pivotroot", "switchroot",
    "container", "runtime", "oci", "cri",
    "runc", "crun", "youki", "gvisor",
    "kata", "firecracker", "cloudhypervisor",
    "strato", "nabla", "unikraft", "osv",
    "linuxkit", "alpine", "busybox",
    "scratch", "from", "base", "image",
    "layer", "manifest", "config", "tag",
    "registry", "hub", "repository",
    "namespace", "pull", "push", "build",
    "run", "exec", "attach", "logs",
    "inspect", "stats", "volume", "mount",
    "bind", "tmpfs", "network", "bridge",
    "host", "overlay", "macvlan", "ipvlan",
    "none", "custom", "port", "expose",
    "publish", "map", "compose", "stack",
    "service", "swarm", "secret", "config",
    "credential", "certificate", "dockerfile",
    "compose", "stack", "spec", "helm",
    "chart", "repo", "release", "kubeconfig",
    "context", "cluster", "namespace",
    "node", "pod", "service", "deployment",
    "statefulset", "daemonset", "job",
    "cronjob", "configmap", "secret", "pv",
    "pvc", "sc", "ingress", "egress",
    "endpoint", "hpa", "vpa", "pdb",
    "networkpolicy", "rbac", "sa", "role",
    "clusterrole", "rolebinding",
    "clusterrolebinding", "crd", "cr",
    "webhook", "admission", "mutating",
    "validating", "conversion", "operator",
    "controller", "reconciler", "informers",
    "listers", "watchers", "caches",
    "apiserver", "scheduler", "controller",
    "etcd", "kubelet", "kubeproxy", "cni",
    "csi", "calico", "flannel", "weave",
    "cilium", "kubeadm", "kubespray",
    "kops", "kind", "minikube", "microk8s",
    "k3s", "k0s", "openshift", "rancher",
    "tanzu", "gke", "eks", "aks", "oke",
    "digitalocean", "scaleway", "vultr",
    "linode", "hetzner", "ovh", "ionos",
    "contabo", "netcup", "strato", "1and1",
    "godaddy", "namecheap", "cloudflare",
    "akamai", "fastly", "cloudfront",
    "varnish", "squid", "traffic", "server",
    "haproxy", "nginx", "apache", "caddy",
    "traefik", "envoy", "linkerd", "istio",
    "consul", "etcd", "zookeeper", "eureka",
    "nacos", "apollo", "spring", "cloud",
    "kafka", "pulsar", "rabbitmq", "activemq",
    "nats", "jetstream", "zeromq", "nanomsg",
    "redis", "memcached", "hazelcast",
    "ignite", "couchbase", "cassandra",
    "scylla", "hbase", "bigtable", "spanner",
    "cockroach", "yugabyte", "tidb",
    "oceanbase", "polardb", "aurora",
    "rds", "dynamodb", "documentdb",
    "neptune", "opensearch", "solr",
    "meilisearch", "typesense", "algolia",
    "elastic", "search", "enterprise",
    "splunk", "datadog", "newrelic",
    "dynatrace", "grafana", "prometheus",
    "thanos", "cortex", "loki", "tempo",
    "mimir", "alloy", "jaeger", "zipkin",
    "skywalking", "pinpoint", "datadog",
    "newrelic", "dynatrace", "appdynamics",
    "sentry", "rollbar", "bugsnag",
    "honeybadger", "pagerduty", "opsgenie",
    "victorops", "icinga", "nagios",
    "zabbix", "alertmanager", "ansible",
    "puppet", "chef", "salt", "terraform",
    "pulumi", "crossplane", "cdk", "packer",
    "vagrant", "waypoint", "nomad", "consul",
    "vault", "boundary", "sentinel",
    "jenkins", "teamcity", "bamboo",
    "circleci", "github", "actions",
    "gitlab", "ci", "travis", "codeship",
    "drone", "woodpecker", "buildkite",
    "argocd", "flux", "jenkins", "spinnaker",
    "harness", "octopus", "deploy", "ship",
    "sonar", "snyk", "dependabot", "renovate",
    "codeql", "semgrep", "gitleaks",
    "trufflehog", "eslint", "prettier",
    "black", "ruff", "mypy", "pyright",
    "pylint", "flake8", "bandit", "safety",
    "pip", "audit", "pipenv", "poetry",
    "pdm", "hatch", "flit", "pip", "conda",
    "mamba", "micromamba", "brew", "apt",
    "yum", "dnf", "pacman", "choco", "scoop",
    "winget", "portage", "nix", "guix",
    "spack", "easybuild", "cargo", "npm",
    "yarn", "pnpm", "bun", "go", "mod",
    "dep", "vgo", "golang", "gem", "bundler",
    "rake", "gemspec", "nuget", "dotnet",
    "paket", "fake", "maven", "gradle",
    "ant", "sbt", "leiningen", "cabal",
    "stack", "hpack", "nix", "opam", "dune",
    "oasis", "jbuilder", "cpan", "cpanm",
    "carton", "perlbrew", "easy_install",
    "wheel", "egg", "pypi", "npm", "rubygems",
    "crates", "nuget", "maven", "central",
    "packagist", "homebrew", "linuxbrew",
    "macports", "fink", "snap", "flatpak",
    "appimage", "portable", "rpm", "deb",
    "pkg", "msi", "exe", "app", "dmg",
    "toolbox", "distrobox", "devcontainer",
    "codespace", "gitpod", "coder", "vscode",
    "dev", "container", "spec", "devfile",
    "openapi", "swagger", "graphql", "grpc",
    "protobuf", "thrift", "avro", "parquet",
    "json", "yaml", "toml", "hcl", "dhall",
    "xml", "html", "css", "js", "ts",
    "wasm", "blazor", "silverlight", "flash",
    "java", "kotlin", "scala", "clojure",
    "groovy", "python", "ruby", "perl",
    "lua", "tcl", "php", "hack", "hhvm",
    "phpt", "javascript", "typescript",
    "coffeescript", "livescript", "c", "cpp",
    "c++", "c#", "objective-c", "swift",
    "rust", "go", "zig", "odin", "haskell",
    "ocaml", "f#", "sml", "coq", "idris",
    "agda", "lean", "purescript", "elixir",
    "erlang", "gleam", "caramel", "julia",
    "matlab", "r", "fortran", "cobol",
    "pascal", "ada", "lisp", "scheme",
    "racket", "clojure", "common", "lisp",
    "emacs", "lisp", "elisp", "guile",
    "prolog", "datalog", "souffle", "asp",
    "sql", "plsql", "tsql", "psql", "mysql",
    "nosql", "newsql", "graph", "document",
    "key", "value", "wide", "column",
    "time", "series", "object", "blob",
    "file", "relational", "dimensional",
    "multidimensional", "oltp", "olap",
    "htap", "data", "warehouse", "lake",
    "mart", "etl", "elt", "data", "pipeline",
    "stream", "batch", "real", "time",
    "near", "real", "lambda", "kappa",
    "medallion", "bronze", "silver", "gold",
    "platinum", "staging", "raw", "refined",
    "curated", "dimension", "fact", "measure",
    "attribute", "snowflake", "star", "galaxy",
    "vault", "slowly", "changing", "dimension",
    "type", "scd", "type1", "type2", "type3",
    "type4", "conformed", "junk", "degenerate",
    "roleplaying", "bridge", "accumulating",
    "snapshot", "transaction", "periodic",
    "accumulating", "kimball", "inmon",
    "data", "vault", "lakehouse", "delta",
    "lake", "iceberg", "hudi", "carbon",
    "paimon", "delta", "spark", "flink",
    "beam", "storm", "heron", "mapreduce",
    "hadoop", "yarn", "hdfs", "hive",
    "presto", "trino", "impala", "drill",
    "tez", "pig", "sqoop", "flume", "kafka",
    "pulsar", "rabbitmq", "activemq",
    "nats", "jetstream", "pulsar", "kafka",
    "kinesis", "firehose", "pubsub",
    "eventhub", "stream", "processing",
    "event", "driven", "cqrs", "eventsourcing",
    "saga", "process", "orchestration",
    "choreography", "state", "machine",
    "state", "machine", "statemachine",
    "workflow", "pipeline", "dag", "task",
    "job", "step", "function", "action",
    "serverless", "lambda", "function",
    "cloud", "faas", "baas", "caas", "paas",
    "iaas", "saas", "daas", "maas", "xaas",
    "onprem", "cloud", "hybrid", "multi",
    "public", "private", "community",
    "sovereign", "edge", "fog", "cloudlet",
    "mist", "green", "brown", "colocation",
    "datacenter", "tier1", "tier2", "tier3",
    "tier4", "ups", "pdu", "crac", "chiller",
    "generator", "pue", "wue", "cue", "erf",
    "rto", "rpo", "mtd", "wrt", "backup",
    "restore", "replicate", "failover",
    "active", "passive", "activeactive",
    "hot", "cold", "warm", "standby",
    "spare", "disaster", "recovery", "dr",
    "bcdr", "business", "continuity",
    "resilience", "chaos", "engineering",
    "monkey", "army", "litmus", "gremlin",
    "chaosmesh", "chaosblade", "failure",
    "injection", "fault", "tolerance",
    "graceful", "degradation", "fallback",
    "circuit", "breaker", "bulkhead",
    "timeout", "retry", "backoff", "jitter",
    "rate", "limit", "concurrency", "throttle",
    "scale", "horizontal", "vertical", "auto",
    "elastic", "capacity", "planning",
    "sizing", "sla", "slo", "sli", "error",
    "budget", "availability", "uptime",
    "downtime", "reliability", "nine",
    "five", "three", "four", "six",
    "percent", "percentage", "ratio", "rate",
    "threshold", "baseline", "target", "goal",
    "kpi", "okr", "metric", "dashboard",
    "report", "analytics", "insight", "trend",
    "forecast", "predict", "estimate",
    "project", "cagr", "yoy", "mom", "qoq",
    "wow", "growth", "decline", "peak",
    "trough", "seasonal", "cyclic", "trend",
    "noise", "outlier", "anomaly", "spike",
    "drop", "mean", "median", "mode", "range",
    "variance", "stddev", "covariance",
    "correlation", "regression", "classification",
    "clustering", "dimensionality", "reduction",
    "pca", "tsne", "umap", "lle", "isomap",
    "mds", "svm", "rf", "gbm", "xgb", "lgbm",
    "cnn", "rnn", "lstm", "gru", "transformer",
    "gan", "vae", "diffusion", "normalizing",
    "flow", "reinforcement", "learning",
    "rl", "drl", "supervised", "unsupervised",
    "semi", "self", "transfer", "multitask",
    "meta", "fewshot", "zeroshot", "oneshot",
    "incontext", "prompt", "fine", "tune",
    "pretrain", "train", "inference", "serving",
    "deploy", "optimize", "distill", "prune",
    "quantize", "compress", "accelerate",
    "parallel", "distribute", "shard",
    "partition", "replicate", "cache",
    "offload", "swap", "pipeline", "tensor",
    "model", "parallelism", "data", "pipeline",
    "tensor", "sequence", "expert", "moefication",
    "moe", "gshard", "switch", "expert",
    "router", "gate", "capacity", "load",
    "balance", "auxiliary", "loss", "zloss",
    "importance", "smooth", "topk", "top2",
    "top1", "noisy", "hash", "random",
    "learned", "routing", "shared", "private",
    "expert", "specialist", "dense", "sparse",
    "mixture", "expert", "attention", "linear",
    "flash", "attention", "page", "attention",
    "vllm", "tgi", "triton", "inference",
    "server", "torchserve", "onnx", "runtime",
    "openvino", "tensorrt", "coreml", "nne",
    "tflite", "edgetpu", "nvidia", "amd",
    "intel", "apple", "google", "tpu", "gpu",
    "cpu", "npu", "dsp", "hbm", "gddr",
    "lpddr", "ddr", "sram", "flops", "tops",
    "tops", "tflops", "bandwidth", "throughput",
    "latency", "batch", "size", "sequence",
    "length", "context", "window", "max",
    "tokens", "tokenizer", "vocab", "embedding",
    "hidden", "layer", "head", "dimension",
    "ffn", "mlp", "activation", "gelu", "relu",
    "silu", "swiglu", "geglu", "reglu",
    "norm", "rmsnorm", "layernorm", "batchnorm",
    "pre", "post", "norm", "sandwich",
    "residual", "skip", "connection", "shortcut",
    "rope", "alibi", "relative", "position",
    "absolute", "learned", "sinusoidal",
    "kv", "cache", "paged", "vllm", "sglang",
    "prefix", "caching", "radix", "tree",
    "speculative", "decoding", "draft",
    "verify", "medusa", "eagle", "lookahead",
    "selfspec", "blockwise", "parallel",
    "decoding", "cascade", "verification",
    "rejection", "sampling", "greedy",
    "beam", "topk", "topp", "temperature",
    "repetition", "penalty", "frequency",
    "presence", "diversity", "typical",
    "eta", "mirostat", "contrastive",
    "classifier", "free", "guidance", "cfg",
    "logit", "processor", "warp", "transform",
    "logits", "processor", "warp", "warp",
    "tail", "free", "sampling", "threshold",
    "epsilon", "cutoff", "eta", "cutoff",
    "minp", "topp", "topk", "typical",
    "repetition", "frequency", "presence",
    "temperature", "dynamic", "threshold",
    "adaptive", "sampler", "logit", "bias",
    "ban", "allow", "block", "good",
    "bad", "words", "ids", "token",
    "eos", "bos", "pad", "unk", "sep", "cls",
    "mask", "sos", "eol", "eof",
    "begin", "end", "separator", "padding",
    "unknown", "class", "mask", "segment",
    "special", "token", "added", "extra",
    "control", "token", "function", "call",
    "tool", "call", "function", "calling",
    "tool", "use", "tool", "calling",
    "parallel", "tool", "call", "multi",
    "streaming", "chunk", "delta", "event",
    "server", "sent", "event", "sse",
    "websocket", "ws", "grpc", "stream",
    "bidirectional", "unidirectional",
    "push", "pull", "pub", "sub",
    "request", "reply", "requestresponse",
    "fire", "forget", "async", "sync",
    "oneway", "twoway", "duplex",
    "rest", "graphql", "grpc", "soap",
    "jsonrpc", "xmlrpc", "thrift", "avro",
    "openapi", "swagger", "asyncapi", "graphql",
    "schema", "registry", "evolution",
    "backward", "forward", "full", "transitive",
    "compatible", "breaking", "deprecated",
    "required", "optional", "nullable",
    "enum", "oneof", "anyof", "allof", "not",
    "ref", "def", "path", "component",
    "security", "scheme", "bearer", "apikey",
    "oauth", "openid", "rate", "limit",
    "quota", "throttle", "retry", "backoff",
    "circuit", "breaker", "idempotent",
    "safe", "cacheable", "conditional",
    "request", "etag", "lastmodified",
    "ifmatch", "ifnonematch", "ifmodified",
    "ifunmodified", "ifrange", "range",
    "content", "range", "partial", "accept",
    "contenttype", "encoding", "language",
    "charset", "negotiation", "content",
    "disposition", "filename", "multipart",
    "formdata", "urlencoded", "chunked",
    "transfer", "encoding", "compression",
    "gzip", "deflate", "br", "zstd", "compress",
    "identity", "keepalive", "connection",
    "upgrade", "websocket", "http2", "http3",
    "quic", "tls", "ssl", "sni", "alpn", "npn",
    "certificate", "chain", "intermediate",
    "root", "ca", "selfsigned", "letsencrypt",
    "acme", "dns01", "http01", "tlsalpn01",
    "wildcard", "san", "cn", "org", "validity",
    "expiry", "revocation", "crl", "ocsp",
    "stapling", "muststaple", "pinning",
    "hpkp", "expectct", "expectstaple",
    "csp", "hsts", "xfo", "xxp", "xss",
    "referrer", "policy", "permissions",
    "feature", "policy", "document", "policy",
    "cors", "origin", "accesscontrol",
    "alloworigin", "allowmethods", "allowheaders",
    "exposeheaders", "maxage", "credentials",
    "preflight", "simple", "request",
    "cookie", "session", "token", "jwt",
    "samesite", "secure", "httponly",
    "domain", "path", "maxage", "expires",
    "csrf", "token", "double", "submit",
    "synchronizer", "encrypted", "hmac",
    "captcha", "recaptcha", "hcaptcha",
    "turnstile", "rate", "limit", "brute",
    "force", "lockout", "account", "takeover",
    "credential", "stuffing", "spraying",
    "password", "hash", "bcrypt", "argon2",
    "scrypt", "pbkdf2", "salted", "pepper",
    "plaintext", "encrypted", "hashed",
    "salting", "peppering", "stretching",
    "key", "derivation", "hkdf", "pbkdf",
    "encryption", "aes", "chacha", "salsa",
    "twofish", "blowfish", "serpent", "des",
    "3des", "rc4", "rc5", "idea", "cast",
    "mode", "cbc", "ecb", "cfb", "ofb",
    "ctr", "gcm", "ccm", "eax", "siv",
    "padding", "pkcs7", "pkcs5", "oaep",
    "pss", "pkcs1", "v15", "v21",
    "rsa", "dsa", "ecdsa", "eddsa",
    "ecdh", "ecies", "dh", "elgamal",
    "curve", "p256", "p384", "p521", "x25519",
    "ed25519", "secp256k1", "bp256", "bp384",
    "key", "exchange", "agreement", "transport",
    "wrap", "unwrap", "encapsulate",
    "sign", "verify", "hash", "digest",
    "signature", "scheme", "rsassa", "ecdsa",
    "eddsa", "schnorr", "bls", "ring",
    "threshold", "multisig", "aggregate",
    "blind", "group", "proxy", "designated",
    "verifier", "undeniable", "failstop",
    "forward", "secure", "deniable",
    "nonrepudiation", "authenticity",
    "integrity", "confidentiality",
    "availability", "accountability",
    "auditability", "traceability",
    "provenance", "attestation", "notarization",
    "timestamp", "seal", "witness",
    "blockchain", "distributed", "ledger",
    "consensus", "pow", "pos", "dpos", "pbft",
    "hotstuff", "tendermint", "cosmos",
    "polkadot", "substrate", "near",
    "ethereum", "evm", "solidity", "vyper",
    "bitcoin", "script", "taproot", "schnorr",
    "lightning", "network", "ln", "rgb",
    "corda", "hyperledger", "fabric",
    "sawtooth", "iroha", "indy", "besu",
    "burrow", "quorum", "pantheon", "tessera",
    "orion", "privacy", "zero", "knowledge",
    "zkp", "snark", "stark", "bulletproof",
    "range", "proof", "circuit", "constraint",
    "witness", "prover", "verifier", "setup",
    "ceremony", "trusted", "setup", "toxic",
    "waste", "transparent", "universal",
    "updateable", "recursive", "aggregation",
    "accumulator", "polynomial", "commitment",
    "kzg", "pedersen", "elgamal", "fujisaki",
    "vector", "commitment", "merkle", "tree",
    "hash", "tree", "trie", "merkle", "patricia",
    "radix", "trie", "smt", "mpt", "patricia",
    "bloom", "filter", "cuckoo", "quotient",
    "xor", "filter", "gcs", "golomb",
    "hyperloglog", "countmin", "sketch",
    "simhash", "minhash", "locality",
    "sensitive", "lsh", "ann", "approx",
    "nearest", "neighbor", "kd", "tree",
    "vp", "tree", "r", "tree", "ball", "tree",
    "cover", "tree", "spill", "tree", "rp",
    "tree", "pq", "tree", "ivf", "hnsw",
    "nsg", "ssg", "efanna", "faiss", "scann",
    "annoy", "nmslib", "puffs", "titan",
    "milvus", "qdrant", "weaviate", "pinecone",
    "chroma", "vespa", "elasticsearch",
    "opensearch", "solr", "redisearch",
    "redisstack", "redislabs", "vald", "vearch",
    "jina", "marqo", "txtai", "langchain",
    "llamaindex", "semantic", "kernel",
    "aisql", "spacy", "stanza", "flair",
    "transformers", "sentence", "transformers",
    "tokenizers", "datasets", "evaluate",
    "accelerate", "huggingface", "hub",
    "model", "dataset", "space", "gradio",
    "streamlit", "bokeh", "dash", "plotly",
    "shiny", "rstudio", "posit", "jupyter",
    "colab", "kaggle", "deepnote", "hex",
    "notebook", "lab", "hub", "enterprise",
    "jupyterlab", "notebook", "classic",
    "voila", "ipywidgets", "ipykernel",
    "ipython", "jupyter", "console",
    "qtconsole", "spyder", "pycharm", "vscode",
    "vim", "neovim", "emacs", "atom",
    "sublime", "textmate", "bbedit", "notepad",
    "notepadpp", "spacemacs", "doomemacs",
    "cursor", "windsurf", "zed", "helix",
    "kakoune", "vis", "acme", "sam", "ed",
    "ex", "vi", "nvi", "nano", "pico", "joe",
    "jstar", "mg", "uemacs", "zile", "jed",
    "dired", "ranger", "lf", "nnn", "vifm",
    "midnight", "commander", "mc", "fzf",
    "skim", "peco", "percol", "ripgrep", "rg",
    "ag", "ack", "grep", "find", "fd",
    "locate", "mlocate", "tree", "exa", "lsd",
    "eza", "bat", "cat", "ccat", "highlight",
    "delta", "diff", "diffso", "difftastic",
    "jq", "yq", "xq", "tq", "entr", "watch",
    "inotify", "fswatch", "tmux", "screen",
    "dtach", "abduco", "byobu", "terminator",
    "kitty", "alacritty", "wezterm", "ghostty",
    "foot", "st", "urxvt", "rxvt", "xterm",
    "terminal", "konsole", "gnome", "terminal",
    "xfce4", "deepin", "terminal", "alacritty",
    "kitty", "wezterm", "ghostty", "iterm2",
    "terminal", "hyper", "warp", "tabby",
    "terminus", "mobaxterm", "putty", "kitty",
    "mintty", "cygwin", "msys2", "mingw",
    "wsl", "wsl2", "bash", "zsh", "fish",
    "nu", "elvish", "xonsh", "powershell",
    "pwsh", "cmd", "sh", "dash", "ksh", "tcsh",
    "csh", "posix", "bourne", "shell",
    "bashism", "shebang", "env", "exec",
    "source", "alias", "export", "unset",
    "readonly", "function", "trap", "test",
    "let", "local", "global", "declare",
    "typeset", "printf", "echo", "read",
    "mapfile", "here", "doc", "here", "string",
    "process", "substitution", "command",
    "substitution", "arithmetic", "expansion",
    "brace", "tilde", "parameter", "variable",
    "globbing", "wildcard", "pattern", "regex",
    "extended", "glob", "globstar", "nullglob",
    "failglob", "dotglob", "nocaseglob",
    "globignore", "shopt", "set", "unset",
    "builtin", "enable", "disable", "type",
    "command", "hash", "cd", "pushd", "popd",
    "dirs", "pwd", "ls", "mkdir", "rmdir",
    "touch", "cp", "mv", "rm", "ln", "chmod",
    "chown", "chgrp", "umask", "stat", "dd",
    "tee", "cat", "tac", "rev", "head", "tail",
    "nl", "wc", "od", "sort", "uniq", "comm",
    "diff", "patch", "cut", "paste", "join",
    "tr", "expand", "unexpand", "fold", "fmt",
    "pr", "sed", "awk", "gawk", "mawk", "nawk",
    "perl", "python", "ruby", "lua", "tcl",
    "expect", "autoexpect", "empty", "cron",
    "at", "batch", "anacron", "service",
    "systemctl", "journalctl", "timedatectl",
    "hostnamectl", "localectl", "loginctl",
    "machinectl", "busctl", "sysctl", "modprobe",
    "insmod", "rmmod", "lsmod", "modinfo",
    "depmod", "dmesg", "journalctl", "logread",
    "kern", "user", "mail", "daemon", "auth",
    "syslog", "lpr", "news", "uucp", "cron",
    "local0", "local7", "fatal", "error",
    "warn", "info", "debug", "trace", "verbose",
    "emerg", "alert", "crit", "err", "warning",
    "notice", "panic", "silly", "log", "level",
    "facility", "priority", "syslog", "rsyslog",
    "syslogng", "journald", "logrotate",
    "logwatch", "logcheck", "graylog",
    "logstash", "fluentd", "fluentbit", "vector",
    "filebeat", "metricbeat", "packetbeat",
    "heartbeat", "winlogbeat", "elastic",
    "stack", "elk", "opensearch", "graylog",
    "splunk", "sumologic", "logz", "datadog",
    "newrelic", "dynatrace", "signalfx",
    "wavefront", "influxdb", "timescaledb",
    "questdb", "clickhouse", "druid", "pinot",
    "kudu", "monetdb", "vertica", "redshift",
    "bigquery", "snowflake", "databricks",
    "athena", "spark", "hive", "impala",
    "drill", "tez", "mr", "mapreduce",
    "hadoop", "yarn", "hdfs", "s3", "gcs",
    "wasb", "adls", "minio", "ceph", "gluster",
    "moosefs", "nfs", "smb", "cifs", "samba",
    "fuse", "9p", "virtio", "plan9", "sshfs",
    "curlftpfs", "s3fs", "goofys", "rclone",
    "rsync", "unison", "syncthing", "nextcloud",
    "owncloud", "seafile", "dropbox",
    "googledrive", "onedrive", "icloud",
    "mega", "pcloud", "box", "backblaze",
    "wasabi", "idrive", "crashplan", "duplicity",
    "duplicati", "borg", "restic", "kopia",
    "restic", "borg", "duplicacy", "tar",
    "gzip", "bzip2", "xz", "zstd", "zip",
    "rar", "7z", "arj", "cab", "lz4", "snappy",
    "lzo", "lzma", "zlib", "deflate", "gzip",
    "compress", "pack", "unpack", "archive",
    "extract", "compress", "decompress",
    "encode", "decode", "serialize",
    "deserialize", "marshal", "unmarshal",
    "pickle", "json", "yaml", "toml", "xml",
    "csv", "tsv", "ssv", "psv", "ini", "cfg",
    "conf", "config", "env", "properties",
    "plist", "reg", "rc", "profile", "bashrc",
    "zshrc", "vimrc", "tmuxconf", "gitconfig",
    "sshconfig", "sshdconfig", "resolv", "hosts",
    "hostname", "fstab", "mtab", "passwd",
    "shadow", "group", "gshadow", "sudoers",
    "suid", "sgid", "sticky",
}

# 确保 WHITELIST 中的实体也在 GARBAGE 中反注册（排除误删）
KEEP = WHITELIST

def main():
    db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "unified_memory.db")
    if not os.path.exists(db_path):
        print(f"DB not found: {db_path}")
        return 1

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    # 1. 获取所有实体名
    cur = conn.execute("SELECT name, entity_type FROM entities GROUP BY name")
    all_entities = {r["name"]: r["entity_type"] for r in cur.fetchall()}
    print(f"KG 当前实体数: {len(all_entities)}")

    # 2. 确定要删除的实体
    to_delete = []
    for name in all_entities:
        if name in KEEP:
            continue
        if name in GARBAGE:
            to_delete.append(name)
            continue
        # 数字/纯字母/纯符号/过短（<2字符）
        if len(name) < 2:
            to_delete.append(name)
            continue
        # 以数字开头的非 IP 实体
        if name[0].isdigit() and not name.replace(".", "").replace(":", "").isdigit():
            to_delete.append(name)
            continue
        # 包含 '=' 或 ':' 的配置项
        if "=" in name or ":" in name:
            to_delete.append(name)
            continue
        # 包含 '条' '个' '种' '位' 等量词
        if any(c in name for c in "条个种位"):
            to_delete.append(name)
            continue
        # 只包含英文+数字+空格+标点，且是通用词模式的
        import re
        if re.match(r'^[\w\s\-\.\+\(\)\[\]\/]+$', name) and len(name.split()) <= 3:
            to_delete.append(name)
            continue

    print(f"待删除实体: {len(to_delete)}")
    print(f"删除列表: {sorted(to_delete)[:20]}...")

    # 3. 删除关系
    for name in to_delete:
        conn.execute("DELETE FROM relations WHERE subject = ? OR object = ?", (name, name))

    # 4. 删除实体
    for name in to_delete:
        conn.execute("DELETE FROM entities WHERE name = ?", (name,))

    conn.commit()

    # 5. 验证
    cur = conn.execute("SELECT COUNT(*) as c FROM entities")
    remaining = cur.fetchone()["c"]
    cur = conn.execute("SELECT COUNT(*) as c FROM relations")
    rel_remaining = cur.fetchone()["c"]
    print(f"清理后实体数: {remaining}")
    print(f"清理后关系数: {rel_remaining}")

    conn.close()
    print("KG 清理完成 ✅")
    return 0

if __name__ == "__main__":
    sys.exit(main())